### PR TITLE
Updated Prediction in Churn_Modelling.ipynb

### PR DESCRIPTION
**Pull request by PranavGupta98**
Improved result with real data and compared with prediction. Restructured test input to conform to the model's input layer and made the output more user-friendly.

### CODE REVIEW

**Comment by amit17133129** [comment]
This is just an overview of ANN. User friendly apps will made on real world problems.

**Comment by PranavGupta98** [comment]
Definitely a good and detailed overview of ANN, just thought of giving it a more clear output.

**Comment by amit17133129** [comment]
Will do project with more friendly UI in future. Thanks for your views 🙂

**Comment by PranavGupta98** [comment]
Anytime😊, I really like your GitHub repository, it's very well managed and lots of interesting projects! Keep up the good work mate👍

**Comment by amit17133129** [comment]
Thank you 😊

**Pull request closed without merging**
